const PERSONAJES = [
    {
        nombre: "Albert Einstein",
        alias: ["einstein"],
        descripcion: "Físico alemán conocido por la teoría de la relatividad y por transformar nuestra comprensión del espacio, el tiempo y la energía.",
        tipo: "real",
        genero: "hombre",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["aleman"],
        idiomas: ["aleman", "ingles"],
        etiquetas: ["cientifico", "fisico", "profesor"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Marie Curie",
        alias: ["curie"],
        descripcion: "Científica polaca-francesa pionera en el estudio de la radiactividad y ganadora de dos premios Nobel en disciplinas distintas.",
        tipo: "real",
        genero: "mujer",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["polaco", "frances"],
        idiomas: ["polaco", "frances"],
        etiquetas: ["cientifico", "fisico", "quimico", "profesor"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Leonardo da Vinci",
        alias: ["leonardo", "da vinci"],
        descripcion: "Artista e inventor italiano del Renacimiento, autor de la Mona Lisa y de numerosos estudios científicos y mecánicos.",
        tipo: "real",
        genero: "hombre",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["italiano"],
        idiomas: ["italiano"],
        etiquetas: ["artista", "pintor", "inventor", "cientifico"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Cleopatra",
        alias: ["cleopatra vii"],
        descripcion: "Reina del antiguo Egipto y última gran gobernante de la dinastía ptolemaica, célebre por su habilidad política.",
        tipo: "real",
        genero: "mujer",
        vivo: false,
        humano: true,
        famoso: true,
        region: "africa",
        nacionalidades: ["egipcio"],
        idiomas: [],
        etiquetas: ["reina", "gobernante", "politico"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Napoleón Bonaparte",
        alias: ["napoleon", "bonaparte"],
        descripcion: "Militar y emperador francés que dominó gran parte de Europa a comienzos del siglo XIX.",
        tipo: "real",
        genero: "hombre",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["frances"],
        idiomas: ["frances"],
        etiquetas: ["militar", "emperador", "gobernante", "politico"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "William Shakespeare",
        alias: ["shakespeare"],
        descripcion: "Dramaturgo y poeta inglés, autor de obras como Hamlet, Macbeth y Romeo y Julieta.",
        tipo: "real",
        genero: "hombre",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["ingles", "britanico"],
        idiomas: ["ingles"],
        etiquetas: ["escritor", "poeta", "dramaturgo", "autor"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Nikola Tesla",
        alias: ["tesla"],
        descripcion: "Inventor e ingeniero conocido por sus aportes fundamentales a los sistemas de corriente alterna.",
        tipo: "real",
        genero: "hombre",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["serbio", "estadounidense"],
        idiomas: ["serbio", "ingles"],
        etiquetas: ["cientifico", "inventor", "ingeniero"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Frida Kahlo",
        alias: ["frida", "kahlo"],
        descripcion: "Pintora mexicana reconocida por sus autorretratos y por una obra profundamente ligada a su identidad y experiencias personales.",
        tipo: "real",
        genero: "mujer",
        vivo: false,
        humano: true,
        famoso: true,
        region: "america",
        nacionalidades: ["mexicano"],
        idiomas: ["espanol"],
        etiquetas: ["artista", "pintor"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Lionel Messi",
        alias: ["messi", "leo messi"],
        descripcion: "Futbolista argentino considerado uno de los mejores jugadores de la historia del deporte.",
        tipo: "real",
        genero: "hombre",
        vivo: true,
        humano: true,
        famoso: true,
        region: "america",
        nacionalidades: ["argentino"],
        idiomas: ["espanol"],
        etiquetas: ["deportista", "futbolista"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Ada Lovelace",
        alias: ["lovelace", "ada"],
        descripcion: "Matemática británica del siglo XIX, conocida por su trabajo sobre la máquina analítica de Charles Babbage y por ser una pionera de la programación.",
        tipo: "real",
        genero: "mujer",
        vivo: false,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["britanico", "ingles"],
        idiomas: ["ingles"],
        etiquetas: ["matematico", "programador", "cientifico"],
        medios: ["historia"],
        poderes: false,
        magia: false,
        universo: "real",
        mascara: false,
        capa: false
    },
    {
        nombre: "Batman",
        alias: ["bruce wayne"],
        descripcion: "Héroe ficticio de DC Comics. Bruce Wayne combate el crimen con inteligencia, entrenamiento y tecnología, sin superpoderes.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: true,
        humano: true,
        famoso: true,
        region: "america",
        nacionalidades: ["estadounidense"],
        idiomas: ["ingles"],
        etiquetas: ["superheroe", "heroe", "detective", "millonario"],
        medios: ["comic", "pelicula", "serie"],
        poderes: false,
        magia: false,
        universo: "dc",
        mascara: true,
        capa: true
    },
    {
        nombre: "Spider-Man",
        alias: ["spiderman", "spider man", "peter parker"],
        descripcion: "Superhéroe de Marvel. Peter Parker obtiene habilidades arácnidas y decide utilizarlas para proteger a los demás.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: true,
        humano: true,
        famoso: true,
        region: "america",
        nacionalidades: ["estadounidense"],
        idiomas: ["ingles"],
        etiquetas: ["superheroe", "heroe", "estudiante"],
        medios: ["comic", "pelicula", "serie"],
        poderes: true,
        magia: false,
        universo: "marvel",
        mascara: true,
        capa: false
    },
    {
        nombre: "Wonder Woman",
        alias: ["mujer maravilla", "diana prince"],
        descripcion: "Guerrera amazona y superheroína de DC Comics, conocida por su fuerza extraordinaria y su defensa de la humanidad.",
        tipo: "ficticio",
        genero: "mujer",
        vivo: true,
        humano: false,
        famoso: true,
        region: "europa",
        nacionalidades: ["amazona"],
        idiomas: ["ingles"],
        etiquetas: ["superheroe", "heroina", "heroe", "guerrero", "princesa"],
        medios: ["comic", "pelicula", "serie"],
        poderes: true,
        magia: false,
        universo: "dc",
        mascara: false,
        capa: false
    },
    {
        nombre: "Harry Potter",
        alias: ["harry"],
        descripcion: "Joven mago protagonista de la saga Harry Potter, estudiante de Hogwarts y enemigo de Lord Voldemort.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: true,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["britanico", "ingles"],
        idiomas: ["ingles"],
        etiquetas: ["mago", "estudiante", "heroe"],
        medios: ["libro", "pelicula"],
        poderes: true,
        magia: true,
        universo: "harry potter",
        mascara: false,
        capa: false
    },
    {
        nombre: "Darth Vader",
        alias: ["vader", "anakin skywalker"],
        descripcion: "Figura central de Star Wars, antiguo Jedi convertido en uno de los ejecutores más temidos del Imperio Galáctico.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: false,
        humano: true,
        famoso: true,
        region: "espacio",
        nacionalidades: [],
        idiomas: [],
        etiquetas: ["villano", "guerrero", "jedi"],
        medios: ["pelicula", "serie"],
        poderes: true,
        magia: false,
        universo: "star wars",
        mascara: true,
        capa: true
    },
    {
        nombre: "Gandalf",
        alias: ["gandalf el gris", "gandalf el blanco"],
        descripcion: "Poderoso mago de la Tierra Media creado por J. R. R. Tolkien y pieza clave en la lucha contra Sauron.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: true,
        humano: false,
        famoso: true,
        region: "tierra media",
        nacionalidades: [],
        idiomas: [],
        etiquetas: ["mago", "heroe"],
        medios: ["libro", "pelicula"],
        poderes: true,
        magia: true,
        universo: "tolkien",
        mascara: false,
        capa: true
    },
    {
        nombre: "Sherlock Holmes",
        alias: ["sherlock", "holmes"],
        descripcion: "Detective ficticio creado por Arthur Conan Doyle, célebre por su capacidad de observación, lógica y deducción.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: true,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["britanico", "ingles"],
        idiomas: ["ingles"],
        etiquetas: ["detective"],
        medios: ["libro", "pelicula", "serie"],
        poderes: false,
        magia: false,
        universo: "sherlock holmes",
        mascara: false,
        capa: false
    },
    {
        nombre: "Elsa",
        alias: ["elsa de frozen"],
        descripcion: "Reina ficticia de Arendelle en Frozen, capaz de crear y controlar hielo y nieve.",
        tipo: "ficticio",
        genero: "mujer",
        vivo: true,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: [],
        idiomas: [],
        etiquetas: ["reina", "princesa"],
        medios: ["pelicula", "animacion"],
        poderes: true,
        magia: true,
        universo: "disney",
        mascara: false,
        capa: true
    },
    {
        nombre: "Superman",
        alias: ["clark kent", "kal el"],
        descripcion: "Superhéroe de DC Comics nacido en Krypton, conocido por su fuerza, vuelo, velocidad y visión de calor.",
        tipo: "ficticio",
        genero: "hombre",
        vivo: true,
        humano: false,
        famoso: true,
        region: "america",
        nacionalidades: ["estadounidense"],
        idiomas: ["ingles"],
        etiquetas: ["superheroe", "heroe", "periodista"],
        medios: ["comic", "pelicula", "serie"],
        poderes: true,
        magia: false,
        universo: "dc",
        mascara: false,
        capa: true
    },
    {
        nombre: "Hermione Granger",
        alias: ["hermione"],
        descripcion: "Bruja ficticia de la saga Harry Potter, destacada por su inteligencia, disciplina y dominio de la magia.",
        tipo: "ficticio",
        genero: "mujer",
        vivo: true,
        humano: true,
        famoso: true,
        region: "europa",
        nacionalidades: ["britanico", "ingles"],
        idiomas: ["ingles"],
        etiquetas: ["mago", "bruja", "estudiante", "heroe"],
        medios: ["libro", "pelicula"],
        poderes: true,
        magia: true,
        universo: "harry potter",
        mascara: false,
        capa: false
    }
];


if (typeof module !== "undefined" && module.exports) { module.exports = PERSONAJES; }
